/*
 * PWM0_config.h
 *
 * Created: 5/10/2024 2:22:49 PM
 *  Author :  D52
 */ 


#ifndef PWM_CONFIG_H_
#define PWM_CONFIG_H_
										/***Macros For PWM Configuration***/
/*Fast PWM0 Mode:
1- PWM0_INVERTING_MODE
2- PWM0_NON_INVERTING_MODE
*/
#define PWM0_MODE    PWM0_NON_INVERTING_MODE										

/*Fast PWM0 Prescaler:
1- PWM_NO_PRESCALER
2- PWM_8_PRESCALER
3- PWM_64_PRESCALER
4- PWM_256_PRESCALER
5- PWM_1024_PRESCALER
*/
#define PWM0_PRESCALER   PWM_64_PRESCALER

/*Fast PWM1 Mode:
1- PWM1_INVERTING_MODE
2- PWM1_NON_INVERTING_MODE
*/
#define PWM1_MODE    PWM1_NON_INVERTING_MODE

/*Fast PWM0 Prescaler:
1- PWM_NO_PRESCALER
2- PWM_8_PRESCALER
3- PWM_64_PRESCALER
4- PWM_256_PRESCALER
5- PWM_1024_PRESCALER
*/
#define PWM1_PRESCALER   PWM_64_PRESCALER

#endif /* PWM_CONFIG_H_ */
